Add Dockerfile for CTF
nishio-kun/arsenal403 pull request #1
Opened 2021-05-27 00:07 UTC by tomokikun

2021-05-27 00:21 UTC, nishio-kun requested changes

2021-05-27 00:21 UTC, nishio-kun commented on environment/README.md
> +--security-opt="seccomp=unconfined"	| Turn off seccomp confinement for the container
空白1文字にして欲しいです。

2021-05-27 00:38 UTC, tomokikun commented on environment/README.md
> +--security-opt="seccomp=unconfined"	| Turn off seccomp confinement for the container
sorry

2021-05-27 00:41 UTC, tomokikun commented on environment/README.md
> +--security-opt="seccomp=unconfined"	| Turn off seccomp confinement for the container
resolved https://github.com/nishio-kun/arsenal403/pull/1/commits/b1bd99969c604c49c6bf6eb81b32494c6e7ddb24

2021-05-28 00:30 UTC, nishio-kun approved these changes

2021-05-28 00:30 UTC, merged